### ISSUE TITLE
Build fails on OS X Yosemite 10.10.1 due to errors in compat.h

### ISSUE THREAD

**Issue by morgant** [leedm777/homebrew-asterisk#10]
Build fails on OS X Yosemite 10.10.1 w/Xcode 6.1.1 (though I'm using GCC 4.8, as described) with the following error (there are more, of course, but all related to this error):

    /usr/local/bin/gcc-4.8 -o pbx_ael.o -c pbx_ael.c -MD -MT pbx_ael.o -MF .pbx_ael.o.d -MP -D_THREAD_SAFE  -I/private/tmp/asterisk-UUBG64/asterisk-12.2.0/include -fno-strict-aliasing  -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libxml2 -pipe -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations  -g3  -D__Darwin__ -mmacosx-version-min=10.6 -O3 -fPIC -DAST_MODULE=\"pbx_ael\"   
    In file included from /usr/include/sys/_endian.h:130:0,
                     from /usr/include/i386/endian.h:99,
                     from /usr/include/machine/endian.h:35,
                     from /usr/include/sys/types.h:81,
                     from /private/tmp/asterisk-UUBG64/asterisk-12.2.0/include/asterisk/compat.h:49,
                     from /private/tmp/asterisk-UUBG64/asterisk-12.2.0/include/asterisk.h:27,
                     from chan_bridge_media.c:35:
    /private/tmp/asterisk-UUBG64/asterisk-12.2.0/include/asterisk/compat.h:97:10: error: expected ')' before '?' token
     uint64_t htonll(uint64_t host64);

Note that the `configure` output shows:

    checking for htonll... no

Full verbose output from `brew install -vd ~/Projects/homebrew-asterisk/asterisk.rb` can be found in [this gist](https://gist.github.com/morgant/d21fd94fa01a30a91ff1).

**Comment by leedm777** [comment]
I think I've finally got a fix for this. Please let me know if you have further issues.
