### ISSUE TITLE
Getting a malloc error

### ISSUE THREAD

**Issue by prashantd** [leedm777/homebrew-asterisk#18]
Hi,
I followed the instructions to install Asterisk on my Mac OS X - Yosemite machine. The installation went without a hiccup. Thanks. But when I try to start the Asterisk server with "asterisk -vvvg -c", I get the following error:
 == Parsing '/usr/local/etc/asterisk/ccss.conf': Found
asterisk(669,0x7fff778c2300) malloc: *** error for object 0x1029693e0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

Please note, it goes fine till the point of parsing ccss.conf. Can you please help me with what is going on?
Some additional info:
The ownership of the Cellar/asterisk folder is with root:wheel.
Have changed the version from 13 to 13.3.2 in the plist

Please let me know if more information is required. Thanks.

**Comment by leedm777** [comment]
I'm looking into this for #17. Haven't quite figured it out yet :-(

**Comment by prashantd** [comment]
Thanks David. The new build installed like a charm. Thanks a ton.
