### ISSUE TITLE
undefined method `undent' 

### ISSUE THREAD

**Issue by lporras** [leedm777/homebrew-asterisk#32]
Getting installation error:

==> Installing asterisk from leedm777/asterisk
==> Installing dependencies for leedm777/asterisk/asterisk: pjsip-asterisk, libogg and speex
==> Installing leedm777/asterisk/asterisk dependency: pjsip-asterisk
==> Downloading http://pjsip.org/release/2.7.1/pjproject-2.7.1.tar.bz2
Already downloaded: /Users/lporras/Library/Caches/Homebrew/downloads/0767ef298a51e962d692f8c77f4fc29111c8653d226ee14f51e7ba43998f6f93--pjproject-2.7.1.tar.bz2
==> Patching
patching file pjmedia/build/Makefile
patching file pjsip/build/Makefile
Error: An exception occurred within a child process:
  NoMethodError: undefined method `undent' for #<String:0x00007fb7910ff4d8>

**Comment by andreslavariega** [comment]
do u have the solution for this issue ?

**Comment by lporras** [comment]
Not yet, I'm not using homebrew-asterisk for now.

**Comment by sosaucily** [comment]
You can get around this by using `brew tap preetsethi/homebrew-asterisk` instead.

See this PR: https://github.com/leedm777/homebrew-asterisk/pull/29
