### ISSUE TITLE
pjsip problem?

### ISSUE THREAD

**Issue by sja** [leedm777/homebrew-asterisk#5]
After installing, I tried to start by hand to see the error messages. I copied my prod settings and modified the paths in asterisk.conf and logger.conf.
Command: `sudo ./sbin/asterisk -fcv`

But starting is aborted with this error:
```
Assertion failed: (mod_evsub.mod.id != -1), function pjsip_evsub_register_pkg, file ../src/pjsip-simple/evsub.c, line 415.
```

When googling, I found this interesting comment: http://lists.digium.com/pipermail/asterisk-users/2013-September/280387.html
But I don't know how to fix it. The last point (loading order) is not the problem, res_pjsip.so is loaded very early.

Complete Output: https://gist.github.com/sja/ba184e3ae1e601bb499a

**Comment by leedm777** [comment]
@sja I was never able to reproduce this, and things have changed a lot since you filed the issue. If you see again with the latest, please reopen.
